version: 2
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"           # Garanta que o requirements.txt esteja aqui
    schedule:
      interval: "daily"      # Ele checa todo dia, mas você pode forçar manual
    open-pull-requests-limit: 10 # Aumente o limite para ele não "esperar" os de Actions
    allow:
      - dependency-type: "all" # Garante que ele olhe diretas e indiretas

  # Configuração para atualizar as próprias versões das Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"